version: '2'

volumes:
  mysql-data:

services:

  web:
    image: nginx:alpine
    volumes:
      - ./:/var/www:delegated
      - ./docker/web/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./:/var/www:delegated
      - ./docker/app/php${APPLICATION_OS}.ini:/usr/local/etc/php/php.ini:delegated
      - ./docker/app/www.conf:/usr/local/etc/php-fpm.d/www.conf

  db:
    image: mysql:5.7
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mysql-data:/var/lib/mysql
      - ./docker/db/app.cnf:/etc/mysql/mysql.conf.d/app.cnf
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=pris
      - MYSQL_USER=pris
      - MYSQL_PASSWORD=pris
    ports:
      - "3307:3306"
